spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=transactions-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.datasource.url=jdbc:postgresql://postgres:5432/gigdb
spring.datasource.username=gig
spring.datasource.password=gig123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
